### ISSUE TITLE
Persisting #05 Error for Netlogo 6.04 and Netlogo 6.1.1

### ISSUE THREAD

**Issue by paulmorio** [NetLogo/R-Extension#22]
Hello R-Extension Team,

I have been using the r-extension for a while (really cool work!) on Windows. Specifically on Netlogo 6.04. Today I replicated the default installation of Netlogo 6.04 and the R-Extension of 16 months ago on a new machine:

(All as administrator)
- Install Netlogo 6.04
- Install R (3.6.1)
- Install the rJava package
- Set the system PATH variable to C:\Program Files\R\R-3.6.1\bin\x64 (Restart after)
- Set the r.home and jri.home.paths variables in the user.properties found in C:\Program Files\NetLogo 6.0.4\app\extensions\r
- Restart and test the R-extension

Unfortunately it persistently gives the 05 error now. For the sake of experiment I have also now done the complete installation using the new instructions on 6.1.1 and it also returns the 05. 

I have tried directly setting the system environment variables R_HOME and JRI_HOME but then NetLogo simply closes when I call extensions [r].

I would appreciate any help!

**Comment by LaCuneta** [comment]
Hey Paul,

Sorry you ran into this trouble with the R extension, and sorry for the delayed reply here.

I definitely recommend using NetLogo 6.1.1 and the latest version of the R extension it comes with.  One step that was recently added to the docs for the R extension for Windows was [about installing the VC++ 2013 runtime](https://github.com/NetLogo/R-Extension/blob/hexy/INSTALLING.md#windows-specific-installation-steps).  Can you give that a try and see if it resolves the issue with NetLogo immediately closing on you?

The second thing to then check is to open the path to the `jri.home.paths` you have set in Windows explorer and confirm that there is a `JRI.jar` file there.  If there is not, [double check the paths inside of R](https://github.com/NetLogo/R-Extension/blob/hexy/INSTALLING.md#determining-rhome-and-jrihomepaths).

If that doesn't help let me know and I'll see if there is anything else we can try.

**Comment by LaCuneta** [comment]
Closing this for now, but feel free to reply on this issue if you need more assistance.
