### ISSUE TITLE
netlogo 6.3 R error #41

### ISSUE THREAD

**Issue by kidstoneszk** [NetLogo/R-Extension#27]
![image](https://user-images.githubusercontent.com/16143841/194740471-ad7d52be-d1f5-4cce-9630-26a8717525a5.png)

when i have installed netlogo 6.3，and open example1 in R example there are a error appear, please help me

**Comment by kidstoneszk** [comment]
netlogo 6.2 R is ok

**Comment by LaCuneta** [comment]
@kidstoneszk Sorry you ran into this issue, and thank you for taking the time to report it to us.  I'm looking into this and will let you know what I find.  

In the meantime, I want to check if [the Simple R extension](https://github.com/NetLogo/SimpleR-Extension) might meet your needs?  It has a less error-prone setup than the R extension that comes bundled with NetLogo, and if it can do what you want with R I'd recommend using it instead.  You can install it [using NetLogo's built-in extension manager](https://github.com/NetLogo/SimpleR-Extension).

**Comment by kidstoneszk** [comment]
@LaCuneta Thank you for your help 
How to change r:setPlotDevice to sr?

**Comment by LaCuneta** [comment]
@kidstoneszk If you're on Windows use `sr:run "windows()"`, if on macOS use `sr:run "quartz()"`, and Linux use `sr:run "x11()"`.  I'm working on getting a `sr:set-plot-device` prim to Simple R that won't be OS-dependent, but it isn't quite done yet.

**Comment by kidstoneszk** [comment]
Thank you very much
an other question is ”r:putagentdf“ => sr:?

**Comment by kidstoneszk** [comment]
such as  (r:putagentdf "ag" turtles "who" "xcor" "ycor" "test")

**Comment by LaCuneta** [comment]
@kidstoneszk Sorry for the delayed reply.  I went ahead and finished up adding the R extension primitives to the Simple R extension.  So if you use NetLogo 6.3.0 and update to the latest Simple R extension you can use those instead.  [`sr:set-agent-data-frame` would be the new primitive](https://github.com/NetLogo/SimpleR-Extension#srset-agent-data-frame) equivalent to what you are looking for.  `sr:set-lot-device` is also there now.  Feel free to open issues in the SimpleR repo if you notice issues with it, or report them to feedback@ccl.northwestern.edu.  I hope that helps!

**Comment by brandesNW** [comment]
This seems resolved.
