### ISSUE TITLE
package 'stats' could not be loaded

### ISSUE THREAD

**Issue by JiaqiZHANG07** [NetLogo/R-Extension#28]
Hi I'm running NetLogo 6.1.1 and R 4.2.1 on Windows. 

When I run the netlogo there are some problem. The script runs well on R studio. The error message was shown as follow:

Extension exception: Error in R-Extension: Error in Eval: 
org.nlogo.api.ExtensionException: Error : package 'stats' could not be loaded

My user.properties file is edited as below:
r.home=C:/PROGRA~1/R/R-42~1.1
jri.home.paths=C:/ProgramData/R/win-library/4.2/rJava/jri
r.lib.paths=C:/ProgramData/R/win-library/4.2;C:/Program Files/R/R-4.2.1/library

Thanks in advance.

**Comment by brandesNW** [comment]
Hi,
We are sorry you ran into this problem. I suggest you try out the Simple R extension which has a simple point and click configuration menu for telling the extension about the location on your system of your R install. It is more straightforward to set up than the bundled R extension which requires the manual creation of a configuration file.
Using it requires switching to NetLogo 6.3, our most recent release<https://ccl.northwestern.edu/netlogo/docs/versions.html>, which I recommend downloading<https://ccl.northwestern.edu/netlogo/download.shtml> and installing.
You can install the Simple R extension using NetLogo's built-in extension manager<http://ccl.northwestern.edu/netlogo/docs/extension-manager.html>.
Examples showing how to use it can be found here<https://github.com/NetLogo/SimpleR-Extension/blob/main/README.md#using>.
Information on switching to Simple R from the bundled R extension is here<https://urldefense.com/v3/__https:/github.com/NetLogo/SimpleR-Extension*transitioning-from-the-old-r-extension__;Iw!!Dq0X2DkFhyF93HkjWTBQKhk!Wxp3riJGAIYA19koGjERjyP-FcvOezeEwvehHcpQNKEKCo0-Yp2siPQucLhkhoDSP1qHkjoA_EIU83ieNMRSdXDJd6kf5S05Cw$>.
Please let us know if this does not solve your problem, and we will look further into the issue.
Thanks,
Aaron


--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling


From: JiaqiZHANG07 ***@***.***>
Date: Monday, December 19, 2022 at 6:51 AM
To: NetLogo/R-Extension ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NetLogo/R-Extension] package 'stats' could not be loaded (Issue #28)

Hi I'm running NetLogo 6.1.1 and R 4.2.1 on Windows.

When I run the netlogo there are some problem. The script runs well on R studio. The error message was shown as follow:

Extension exception: Error in R-Extension: Error in Eval:
org.nlogo.api.ExtensionException: Error : package 'stats' could not be loaded

My user.properties file is edited as below:
r.home=C:/PROGRA1/R/R-421.1
jri.home.paths=C:/ProgramData/R/win-library/4.2/rJava/jri
r.lib.paths=C:/ProgramData/R/win-library/4.2;C:/Program Files/R/R-4.2.1/library

Thanks in advance.

**Comment by professorbeautiful** [comment]
Thanks, this is exciting!
It wasn't enough to have Rscript on the PATH, or to type the path
/usr/local/bin/Rscript  into the configuration box.
But if I used the Browse... button, and browsed to /usr/local/bin/Rscript,
it followed the soft link to
/Library/Frameworks/R.framework/Versions/4.2/Resources/bin/
& now it is working!

**Comment by brandesNW** [comment]
User problem was solved.
