### ISSUE TITLE
Error #04 on Windows

### ISSUE THREAD

**Issue by edmizac** [NetLogo/R-Extension#29]
Hi all,

I have two machines that run the R extension perfectly. I need to make it run in a third one, but this one is giving me headaches. It has Windows 10 Pro.

Here's what RStudio (and R base) returns when I ask the paths:
![image](https://github.com/NetLogo/R-Extension/assets/72988462/f4ef872c-d70d-484f-81a2-18907ef7878e)

Here's my user.properties in "C:\Users\user\AppData\Roaming\NetLogo\6.3\r":
![image](https://github.com/NetLogo/R-Extension/assets/72988462/3b84cd1e-8a62-4474-95b8-34c6a07f1f47)

Here's my sessionInfo():
![image](https://github.com/NetLogo/R-Extension/assets/72988462/54c05506-ff76-4d1f-9a5a-c452a80bbaf0)

And here are my paths (I have tried with "~" and without it). I have also tried including them as user variables instead of system variables:
![image](https://github.com/NetLogo/R-Extension/assets/72988462/44f50d1a-5da8-45da-873e-ebf268659ff4)

I believe it is linked somehow to the user permission in Windows (although I have installed everything as admin). Am I missing something? 

Thank you for your attention,

**Edit**

I have added an environmental variable R_HOME manually as recommended [here](https://github.com/NetLogo/R-Extension/issues/20#issuecomment-622045715) and let only the 'bin\64' on the PATH. Now I got the Error04 #9 but with some details I have never seen:

![image](https://github.com/NetLogo/R-Extension/assets/72988462/40c4be09-78ac-42d5-bc7c-53b3583f4506)

**Comment by LaCuneta** [comment]
Sorry for the delay in the reply.

My first advice would be to switch to [the Simple R Extension](https://github.com/NetLogo/SimpleR-Extension) if possible.  I know that sounds drastic, but we have [a section on migrating from the R Extension](https://github.com/NetLogo/SimpleR-Extension#transitioning-from-the-old-r-extension) and most prims map directly over.  The Simple R Extension is much simpler to setup, you merely need to choose your `RScript` binary location (or have it on the `PATH`) and the rest should just work.  I see your other posts on issues in this repository, so I'm sure you'll understand that the R Extension's setup is unfortunately very finicky.  The Simple R Extension is available for download and install in [the Extensions Manager](https://ccl.northwestern.edu/netlogo/docs/extension-manager.html) inside the NetLogo app.

As for the error you're encountering, my first guess is that it has to do with a Java conflict.  rJava uses the system Java, whereas NetLogo uses its own bundled Java.  If you run `java -version` at a command prompt, what do you see?  That's what rJava would pick up.  NetLogo 6.3.0 comes bundled with Java 17, so for interop rJava would need a Java runtime of that same version.

The only other thing I can think of, but it should cause error #4 and not #5, is the C++ runtime.  On Windows, sometimes the Visual C++ 2013 runtime packages are needed; you can grab them from Microsoft: https://www.microsoft.com/en-us/download/details.aspx?id=40784

I hope that helps.  Let me know if you can't get anything working and I'll try to come up with something else.

**Comment by edmizac** [comment]
Thanks for your reply, Jeremy. I had no idea there was a simple R extension. I will see what a I can do.

But more importantly: I am actually getting Error #4, not #5. I have renamed the issue. Sorry about this.

That's the output from java -version:
```
PS C:\Users\user> java -version
java version "1.8.0_371"
Java(TM) SE Runtime Environment (build 1.8.0_371-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.371-b11, mixed mode)
```

I have installed JDK 17 and rebooted. But still the same error. Now I have:
```
java version "17.0.7" 2023-04-18 LTS
Java(TM) SE Runtime Environment (build 17.0.7+8-LTS-224)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.7+8-LTS-224, mixed mode, sharing)
```

About Visual C++: I have it already. 

Thank you for you attention,

**Comment by edmizac** [comment]
OK, I have installed JDK 17, redefined JAVA_PATH, reinstaled rJava. Got Error #2. Then, I corrected the user.properties and got back to the same Error #04. 

I will try the simple R extension and I will come back if I have news. Thank you!

**Comment by brandesNW** [comment]
Hi - Did the simple R extension resolve your problem?

**Comment by edmizac** [comment]
@brandesNW yes. I still had some issues there, but not as complicated as with the R extension.
