### ISSUE TITLE
r:eval issue

### ISSUE THREAD

**Issue by ThePengwyn** [NetLogo/R-Extension#8]
Issues I am having

1: r:__evaldirect "<command>" cannot access the netlogo environment
2: when trying to bypass this by using r:put "<variablename>" VALUE, the netlogo environment can access the variable via r:get "<variablename>" but the r:interactiveShell environment cannot
3: r:get "<variablename>" CAN access variables stored in the interactiveShell
4: r:eval seems entirely broken

Upon trying to run r:eval I recieve this error

Extension exception: Error in R-Extension: Error in Eval: 
org.rosuda.REngine.REngineEvalException: error during evaluation
error while observer running R:EVAL
  called by procedure RESETDATA
  called by Button 'ResetData'

org.nlogo.nvm.WrappedExtensionException: Extension exception: Error in R-Extension: Error in Eval: 
org.rosuda.REngine.REngineEvalException: error during evaluation
 at org.nlogo.prim._extern.perform(_extern.java:40)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
 at scala.util.control.Exception$Catch.apply(Exception.scala:224)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)
Caused by: org.nlogo.api.ExtensionException: Error in R-Extension: Error in Eval: 
org.rosuda.REngine.REngineEvalException: error during evaluation
 at org.nlogo.extension.r.Entry$Eval.perform(Entry.java:698)
 at org.nlogo.prim._extern.perform(_extern.java:36)
 ... 8 more
Caused by: org.rosuda.REngine.REngineEvalException: error during evaluation
 at org.rosuda.REngine.JRI.JRIEngine.eval(JRIEngine.java:283)
 at org.rosuda.REngine.REngine.parseAndEval(REngine.java:102)
 at org.nlogo.extension.r.HoldRengineX.execute(HoldRengineX.java:86)
 at org.nlogo.extension.r.Entry$Eval.perform(Entry.java:695)
 ... 9 more

NetLogo 6.0.1
main: org.nlogo.app.AppFrame
thread: JobThread
Java HotSpot(TM) 64-Bit Server VM 1.8.0_121 (Oracle Corporation; 1.8.0_121-b13)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.1
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Assignment3

08:31:43.221 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
08:31:43.217 RuntimeErrorEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
08:31:43.088 AddJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
08:31:42.974 InputBoxLoseFocusEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
08:31:42.903 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
08:31:42.903 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
08:31:42.903 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
08:31:42.903 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
08:31:42.903 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
08:31:42.903 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by mrerrormessage** [comment]
Can you provide your R version information and the contents of your `user.properties` file? Thanks!

**Comment by ThePengwyn** [comment]
Hi mrerrormessage, thanks for responding :)

R version is 3.3.2

User Properties File (same problems on two computers):

Linux:
r.home=/usr/lib64/R
jri.home.paths=/home/Peng/R/x86/_64-pc-linux-gnu-library/3.4/rJava/jri
r.lib.paths=/usr/lib64/R/lib.paths

Windows: 
  (sorry the tilda between the "A" and "1" and the tilda between "3" and "1" are causing a strikeout rather than being parsed as characters)
r.home=C:/PROGRA~1/R/R-33~1.2
jri.home.paths=C:\\Users\\Peng\\Documents\\R\\win-library\\3.3\\rJava\\jri\\
r.lib.paths=C:\\Program Files\\R\\3-3.3.2\\library

**Comment by mrerrormessage** [comment]
Based on the information you posted, it seems that this problem is happening in Windows as well as Linux - is that correct?

Based on the information you've provided so far, I want to make sure we're on the same page with a few things:

* I installed Windows R to the default location and my r.lib.paths is `C:\Program Files\R\R-3.3.2\library`. Your r.lib.paths is slightly different - was there a typo either in your post or in your configuration file?
* When you say that `r:eval` is broken, are there particular commands it can run without erroring? For instance, can it run simple operations like `a <- 1` or expressions like `a <- 2 + 2`. If it can run simple operations, what are the commands which you're having trouble running?
* Are you seeing any errors when loading the R extension, or only when trying to run the `r:eval` command?
* Have you customized your ".Rprofile" or "Rprofile.site" files?
* Are you running any R commands which adjust the R working directory? 
* Regarding the NetLogo environment, as mentioned in the documentation it lives in `nl.env`. Can you run the following commands in the command center and let me know if any lines error (and if so which ones):

```netlogo
r:eval "a <- 2 + 2"  ; creates 'a' in nl.env, sets to 4 (no output)
show r:get "a" ; reads 'a' from nl.env, should print '4'
r:__evaldirect "b <- get('a', nl.env)" ; creates 'b' in global environment (no output)
show r:get "b" ; reads 'b' from global environment, should print '4'
```

If we're so-far-so-good on these commands, open up the interactive shell with `r:interactiveShell` and run the following (again, preferably one at a time):

```R
get('a', nl.env) # should contain 4
b # should also contain 4
```

**Comment by ThePengwyn** [comment]
The same behaviour is occuring in both a Windows and in a Linux system, both distinct computer (no virtual machine usage)

R is in the default path C:\Program Files\R\R-3.3.2\library, when changing the user file it does not change the behaviour.

r:eval "x <- 2" will not pull an error message in netlogo, but the variable will not be stored in the interactiveShell environment, the error message will pop up for the same command different syntax; r:eval "x = 2".

I have not edited either ".Rprofile" or "Rprofile.site" files

The only R commands I am trying to run at this point are basic variable storing commands as exampled above "x <- 2" and "x = 2

r:get WILL retrieve '2' when stored via "x <- 2", however in the interactiveShell, running "x" it will return "Error: object 'x' not found"
when runing "get('x', n1.env)" it will return "Error in get("x", n1.env) : object 'n1.env' not found"

**Comment by mrerrormessage** [comment]
Sorry, I think there's a slight misunderstanding in `get("x", nl.env)`, the character after n is lower-case L, not 1. 

Also, what does running `.libPaths()` in your R environment return? Your `r.lib.paths` values look correct, but they're only searching a single location. If you have libraries that it's trying to located which are installed for your user only and you're providing the system path, NetLogo may be unable to locate those libraries.
